kind: Cluster
name: homelab-dev
talos:
  version: v1.6.7
kubernetes:
  version: 1.29.3
features:
  enableWorkloadProxy: true
patches:
  - name: cni
    file: patches/cni.yaml
---
kind: ControlPlane
machineClass:
  name: homelab-control-plane
  size: 3
patches:
  - name: argocd
    file: patches/argocd.yaml
  - name: monitoring
    file: patches/monitoring.yaml
---
kind: Workers
name: workers
machineClass:
  name: homelab-worker
  size: unlimited
