# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-staging-nginx
#   name: kubelize-nextra
#   namespace: kubelize-nextra
# spec:
#   tls:
#   - hosts:
#     - docs.kubelize.com
#     secretName: kubelize-nextra-tls
#   ingressClassName: nginx
#   rules:
#   - host: docs.kubelize.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: kubelize-nextra
#             port:
#               number: 80