apiVersion: v1
kind: Service
metadata:
  name: arduino-magnet-sensor
  namespace: arduino-magnet-sensor
spec:
  selector:
    app: arduino-magnet-sensor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort