apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
  namespace: renovate
data:
  LOG_LEVEL: ZGVidWc=
  RENOVATE_AUTODISCOVER: ZmFsc2U=
  RENOVATE_BASE_DIR: L3RtcC9yZW5vdmF0ZS8=
  RENOVATE_CONFIG_FILE: L29wdC9yZW5vdmF0ZS9jb25maWcuanNvbg==
  RENOVATE_PLATFORM: Z2l0aHVi
  RENOVATE_TOKEN: Z2hwX05QM0s1T1duM0lTZ0VCUzU5ME5mZGtKM2tGb1lrMzJwWWVRTg==
type: Opaque