apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubelize/homelab
      path: clusters/prod/reservoir/namespaces
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd