apiVersion: batch/v1
kind: CronJob
metadata:
  name: rei-nginx-sync
  namespace: rei-nginx
spec:
  schedule: "*/1 * * * *"  # Cron expression for running every 5 minutes
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: rei-nginx
        spec:
          containers:
          - name: rei-nginx-sync
            image: moffoso/sync-rei-nginx:0.0.7
            volumeMounts:
            - name: rei-nginx-data
              mountPath: /tmp/new
          volumes:
          - name: rei-nginx-data
            hostPath:
              path: /media/kubevirt-hpp/pvc-47196726-6a23-4886-bc6e-dbc6f13f58e5
          restartPolicy: OnFailure
