apiVersion: batch/v1
kind: CronJob
metadata:
  name: rei-nginx-sync
  namespace: rei-nginx
spec:
  schedule: "0 1 * * *"  # Cron expression for running every 5 minutes
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: rei-nginx
        spec:
          containers:
          - name: rei-nginx-sync
            image: kubelize/rsync:0.0.1
            volumeMounts:
            - name: rei-nginx-data
              mountPath: /tmp/website
            - name: sync-script
              mountPath: /usr/local/bin/sync.sh
              subPath: sync.sh
          volumes:
          - name: rei-nginx-data
            hostPath:
              path: /media/kubevirt-hpp/pvc-6e04ad4c-7b48-4fba-b407-99d900f26662
          - name: sync-script
            configMap:
              name: sync-script
          restartPolicy: OnFailure
