apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/malahayatii/homelab
      path: clusters/dev/reservoir/secrets
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd